window.NEXUS_PRODUCTS = [
  {
    "id": 1,
    "sourceNo": 1,
    "article": "NX-SKS-001",
    "slug": "nx-sks-001",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Кабель витая пара",
    "subcategorySlug": "sks-komplekt-sub-1",
    "name": "UTP Cat.5e PVC, 305 м",
    "specification": "Бухта 305 м, медь/CCA уточнить, PVC",
    "unit": "бухта",
    "moq": 10,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": true,
    "brand": "Nexus",
    "sort": 1,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 2,
    "sourceNo": 2,
    "article": "NX-SKS-002",
    "slug": "nx-sks-002",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Кабель витая пара",
    "subcategorySlug": "sks-komplekt-sub-1",
    "name": "UTP Cat.5e LSZH, 305 м",
    "specification": "Бухта 305 м, LSZH",
    "unit": "бухта",
    "moq": 10,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 2,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 3,
    "sourceNo": 3,
    "article": "NX-SKS-003",
    "slug": "nx-sks-003",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Кабель витая пара",
    "subcategorySlug": "sks-komplekt-sub-1",
    "name": "UTP Cat.6 PVC, 305 м",
    "specification": "Бухта 305 м, PVC",
    "unit": "бухта",
    "moq": 10,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": true,
    "brand": "Nexus",
    "sort": 3,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 4,
    "sourceNo": 4,
    "article": "NX-SKS-004",
    "slug": "nx-sks-004",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Кабель витая пара",
    "subcategorySlug": "sks-komplekt-sub-1",
    "name": "UTP Cat.6 LSZH, 305 м",
    "specification": "Бухта 305 м, LSZH",
    "unit": "бухта",
    "moq": 10,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 4,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 5,
    "sourceNo": 5,
    "article": "NX-SKS-005",
    "slug": "nx-sks-005",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Кабель витая пара",
    "subcategorySlug": "sks-komplekt-sub-1",
    "name": "FTP Cat.6 LSZH, 305 м",
    "specification": "Экранированный, LSZH",
    "unit": "бухта",
    "moq": 5,
    "priority": "Средний",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 5,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 6,
    "sourceNo": 6,
    "article": "NX-SKS-006",
    "slug": "nx-sks-006",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Кабель витая пара",
    "subcategorySlug": "sks-komplekt-sub-1",
    "name": "U/FTP Cat.6A LSZH, 305 м",
    "specification": "Cat.6A, LSZH",
    "unit": "бухта",
    "moq": 2,
    "priority": "Низкий/средний",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 6,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "Под заказ"
  },
  {
    "id": 7,
    "sourceNo": 7,
    "article": "NX-SKS-007",
    "slug": "nx-sks-007",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Патч-панели",
    "subcategorySlug": "sks-komplekt-sub-2",
    "name": "Патч-панель Cat.5e UTP 24 порта",
    "specification": "19\", 1U",
    "unit": "шт",
    "moq": 20,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": true,
    "brand": "Nexus",
    "sort": 7,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 8,
    "sourceNo": 8,
    "article": "NX-SKS-008",
    "slug": "nx-sks-008",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Патч-панели",
    "subcategorySlug": "sks-komplekt-sub-2",
    "name": "Патч-панель Cat.6 UTP 24 порта",
    "specification": "19\", 1U",
    "unit": "шт",
    "moq": 20,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 8,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 9,
    "sourceNo": 9,
    "article": "NX-SKS-009",
    "slug": "nx-sks-009",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Патч-панели",
    "subcategorySlug": "sks-komplekt-sub-2",
    "name": "Патч-панель Cat.6 FTP 24 порта",
    "specification": "Экранированная",
    "unit": "шт",
    "moq": 10,
    "priority": "Средний",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 9,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 10,
    "sourceNo": 10,
    "article": "NX-SKS-010",
    "slug": "nx-sks-010",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Патч-панели",
    "subcategorySlug": "sks-komplekt-sub-2",
    "name": "Пустая патч-панель под keystone 24 порта",
    "specification": "19\", универсальная",
    "unit": "шт",
    "moq": 20,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": true,
    "brand": "Nexus",
    "sort": 10,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 11,
    "sourceNo": 11,
    "article": "NX-SKS-011",
    "slug": "nx-sks-011",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Keystone-модули",
    "subcategorySlug": "sks-komplekt-sub-3",
    "name": "Keystone RJ-45 Cat.5e UTP",
    "specification": "180°, белый",
    "unit": "шт",
    "moq": 200,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 11,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 12,
    "sourceNo": 12,
    "article": "NX-SKS-012",
    "slug": "nx-sks-012",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Keystone-модули",
    "subcategorySlug": "sks-komplekt-sub-3",
    "name": "Keystone RJ-45 Cat.6 UTP",
    "specification": "Безынструментальный/110",
    "unit": "шт",
    "moq": 200,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 12,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 13,
    "sourceNo": 13,
    "article": "NX-SKS-013",
    "slug": "nx-sks-013",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Keystone-модули",
    "subcategorySlug": "sks-komplekt-sub-3",
    "name": "Keystone RJ-45 Cat.6 FTP",
    "specification": "Экранированный",
    "unit": "шт",
    "moq": 100,
    "priority": "Средний",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 13,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 14,
    "sourceNo": 14,
    "article": "NX-SKS-014",
    "slug": "nx-sks-014",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Keystone-модули",
    "subcategorySlug": "sks-komplekt-sub-3",
    "name": "Keystone RJ-45 Cat.6A FTP",
    "specification": "Экранированный Cat.6A",
    "unit": "шт",
    "moq": 50,
    "priority": "Низкий/средний",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 14,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "Под заказ"
  },
  {
    "id": 15,
    "sourceNo": 15,
    "article": "NX-SKS-015",
    "slug": "nx-sks-015",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Патч-корды",
    "subcategorySlug": "sks-komplekt-sub-4",
    "name": "Патч-корд Cat.5e UTP 1 м",
    "specification": "серый/синий",
    "unit": "шт",
    "moq": 200,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 15,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 16,
    "sourceNo": 16,
    "article": "NX-SKS-016",
    "slug": "nx-sks-016",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Патч-корды",
    "subcategorySlug": "sks-komplekt-sub-4",
    "name": "Патч-корд Cat.5e UTP 2 м",
    "specification": "серый/синий",
    "unit": "шт",
    "moq": 200,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 16,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 17,
    "sourceNo": 17,
    "article": "NX-SKS-017",
    "slug": "nx-sks-017",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Патч-корды",
    "subcategorySlug": "sks-komplekt-sub-4",
    "name": "Патч-корд Cat.6 UTP 1 м",
    "specification": "серый/синий",
    "unit": "шт",
    "moq": 200,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 17,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 18,
    "sourceNo": 18,
    "article": "NX-SKS-018",
    "slug": "nx-sks-018",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Патч-корды",
    "subcategorySlug": "sks-komplekt-sub-4",
    "name": "Патч-корд Cat.6 UTP 2 м",
    "specification": "серый/синий",
    "unit": "шт",
    "moq": 200,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 18,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 19,
    "sourceNo": 19,
    "article": "NX-SKS-019",
    "slug": "nx-sks-019",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "Патч-корды",
    "subcategorySlug": "sks-komplekt-sub-4",
    "name": "Патч-корд Cat.6 FTP 2 м",
    "specification": "серый",
    "unit": "шт",
    "moq": 100,
    "priority": "Средний",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 19,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "Под заказ"
  },
  {
    "id": 20,
    "sourceNo": 20,
    "article": "NX-SKS-020",
    "slug": "nx-sks-020",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "19\" аксессуары",
    "subcategorySlug": "sks-komplekt-sub-5",
    "name": "Кабельный органайзер 19\", 1U, с кольцами",
    "specification": "металл/пластик",
    "unit": "шт",
    "moq": 50,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 20,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "В наличии"
  },
  {
    "id": 21,
    "sourceNo": 21,
    "article": "NX-SKS-021",
    "slug": "nx-sks-021",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "19\" аксессуары",
    "subcategorySlug": "sks-komplekt-sub-5",
    "name": "Кабельный органайзер 19\", 1U, с крышкой",
    "specification": "металл/пластик",
    "unit": "шт",
    "moq": 50,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 21,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "Под заказ"
  },
  {
    "id": 22,
    "sourceNo": 22,
    "article": "NX-SKS-022",
    "slug": "nx-sks-022",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "19\" аксессуары",
    "subcategorySlug": "sks-komplekt-sub-5",
    "name": "Полка 19\" стационарная",
    "specification": "глубина уточнить",
    "unit": "шт",
    "moq": 20,
    "priority": "Средний",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 22,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "Под заказ"
  },
  {
    "id": 23,
    "sourceNo": 23,
    "article": "NX-SKS-023",
    "slug": "nx-sks-023",
    "group": "СКС-комплект",
    "categorySlug": "sks-komplekt",
    "subgroup": "19\" аксессуары",
    "subcategorySlug": "sks-komplekt-sub-5",
    "name": "PDU 19\" блок розеток",
    "specification": "6–8 розеток",
    "unit": "шт",
    "moq": 20,
    "priority": "Средний",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 23,
    "image": "assets/product-sks-komplekt.svg",
    "availability": "Под заказ"
  },
  {
    "id": 24,
    "sourceNo": 24,
    "article": "NX-FLR-024",
    "slug": "nx-flr-024",
    "group": "Лючки и напольные коробки",
    "categorySlug": "lyuchki-i-napolnye-korobki",
    "subgroup": "Напольные лючки",
    "subcategorySlug": "lyuchki-i-napolnye-korobki-sub-1",
    "name": "Лючок напольный 4 поста ",
    "specification": "металл/пластик, 45x45",
    "unit": "шт",
    "moq": 50,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": true,
    "brand": "Nexus",
    "sort": 24,
    "image": "assets/product-lyuchki-i-napolnye-korobki.svg",
    "availability": "В наличии"
  },
  {
    "id": 25,
    "sourceNo": 25,
    "article": "NX-FLR-025",
    "slug": "nx-flr-025",
    "group": "Лючки и напольные коробки",
    "categorySlug": "lyuchki-i-napolnye-korobki",
    "subgroup": "Напольные лючки",
    "subcategorySlug": "lyuchki-i-napolnye-korobki-sub-1",
    "name": "Лючок напольный 6 постов",
    "specification": "металл, 45x45",
    "unit": "шт",
    "moq": 50,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 25,
    "image": "assets/product-lyuchki-i-napolnye-korobki.svg",
    "availability": "В наличии"
  },
  {
    "id": 26,
    "sourceNo": 26,
    "article": "NX-FLR-026",
    "slug": "nx-flr-026",
    "group": "Лючки и напольные коробки",
    "categorySlug": "lyuchki-i-napolnye-korobki",
    "subgroup": "Напольные лючки",
    "subcategorySlug": "lyuchki-i-napolnye-korobki-sub-1",
    "name": "Лючок напольный 8 постав",
    "specification": "металл, 45x45",
    "unit": "шт",
    "moq": 30,
    "priority": "Средний",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 26,
    "image": "assets/product-lyuchki-i-napolnye-korobki.svg",
    "availability": "В наличии"
  },
  {
    "id": 27,
    "sourceNo": 27,
    "article": "NX-FLR-027",
    "slug": "nx-flr-027",
    "group": "Лючки и напольные коробки",
    "categorySlug": "lyuchki-i-napolnye-korobki",
    "subgroup": "Напольные лючки",
    "subcategorySlug": "lyuchki-i-napolnye-korobki-sub-1",
    "name": "Лючок под плитку/керамогранит 6–8 модулей",
    "specification": "скрытый монтаж",
    "unit": "шт",
    "moq": 20,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": true,
    "brand": "Nexus",
    "sort": 27,
    "image": "assets/product-lyuchki-i-napolnye-korobki.svg",
    "availability": "Под заказ"
  },
  {
    "id": 28,
    "sourceNo": 28,
    "article": "NX-FLR-028",
    "slug": "nx-flr-028",
    "group": "Лючки и напольные коробки",
    "categorySlug": "lyuchki-i-napolnye-korobki",
    "subgroup": "Напольные коробки",
    "subcategorySlug": "lyuchki-i-napolnye-korobki-sub-2",
    "name": "Коробка напольная под стяжку 4–6 модулей",
    "specification": "основание/монтажная коробка",
    "unit": "шт",
    "moq": 50,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 28,
    "image": "assets/product-lyuchki-i-napolnye-korobki.svg",
    "availability": "В наличии"
  },
  {
    "id": 29,
    "sourceNo": 30,
    "article": "NX-FLR-030",
    "slug": "nx-flr-030",
    "group": "Лючки и напольные коробки",
    "categorySlug": "lyuchki-i-napolnye-korobki",
    "subgroup": "Аксессуары к лючкам",
    "subcategorySlug": "lyuchki-i-napolnye-korobki-sub-3",
    "name": "адаптеры 45x45",
    "specification": "под розетки и keystone",
    "unit": "шт",
    "moq": 200,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 29,
    "image": "assets/product-lyuchki-i-napolnye-korobki.svg",
    "availability": "В наличии"
  },
  {
    "id": 30,
    "sourceNo": 31,
    "article": "NX-FLR-031",
    "slug": "nx-flr-031",
    "group": "Лючки и напольные коробки",
    "categorySlug": "lyuchki-i-napolnye-korobki",
    "subgroup": "Аксессуары к лючкам",
    "subcategorySlug": "lyuchki-i-napolnye-korobki-sub-3",
    "name": "Заглушки/разделители/крепеж",
    "specification": "комплекты",
    "unit": "шт",
    "moq": 200,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 30,
    "image": "assets/product-lyuchki-i-napolnye-korobki.svg",
    "availability": "В наличии"
  },
  {
    "id": 31,
    "sourceNo": 32,
    "article": "NX-MOD-032",
    "slug": "nx-mod-032",
    "group": "Розетки и модули",
    "categorySlug": "rozetki-i-moduli",
    "subgroup": "Силовые розетки",
    "subcategorySlug": "rozetki-i-moduli-sub-1",
    "name": "Розетка 220В одинарная белая",
    "specification": "45x45, с заземлением",
    "unit": "шт",
    "moq": 200,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 31,
    "image": "assets/product-rozetki-i-moduli.svg",
    "availability": "В наличии"
  },
  {
    "id": 32,
    "sourceNo": 34,
    "article": "NX-MOD-034",
    "slug": "nx-mod-034",
    "group": "Розетки и модули",
    "categorySlug": "rozetki-i-moduli",
    "subgroup": "UPS-розетки",
    "subcategorySlug": "rozetki-i-moduli-sub-2",
    "name": "Розетка 220В красная ",
    "specification": "45x45, с заземлением",
    "unit": "шт",
    "moq": 200,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": true,
    "brand": "Nexus",
    "sort": 32,
    "image": "assets/product-rozetki-i-moduli.svg",
    "availability": "В наличии"
  },
  {
    "id": 33,
    "sourceNo": 35,
    "article": "NX-MOD-035",
    "slug": "nx-mod-035",
    "group": "Розетки и модули",
    "categorySlug": "rozetki-i-moduli",
    "subgroup": "Слаботочные модули",
    "subcategorySlug": "rozetki-i-moduli-sub-3",
    "name": "Модуль RJ-45 Cat.5e UTP",
    "specification": "45x45 или keystone-адаптер",
    "unit": "шт",
    "moq": 200,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 33,
    "image": "assets/product-rozetki-i-moduli.svg",
    "availability": "В наличии"
  },
  {
    "id": 34,
    "sourceNo": 36,
    "article": "NX-MOD-036",
    "slug": "nx-mod-036",
    "group": "Розетки и модули",
    "categorySlug": "rozetki-i-moduli",
    "subgroup": "Слаботочные модули",
    "subcategorySlug": "rozetki-i-moduli-sub-3",
    "name": "Модуль RJ-45 Cat.6 UTP",
    "specification": "45x45 или keystone-адаптер",
    "unit": "шт",
    "moq": 200,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 34,
    "image": "assets/product-rozetki-i-moduli.svg",
    "availability": "В наличии"
  },
  {
    "id": 35,
    "sourceNo": 37,
    "article": "NX-MOD-037",
    "slug": "nx-mod-037",
    "group": "Розетки и модули",
    "categorySlug": "rozetki-i-moduli",
    "subgroup": "Слаботочные модули",
    "subcategorySlug": "rozetki-i-moduli-sub-3",
    "name": "Модуль HDMI/USB Type-C",
    "specification": "мультимедийные модули",
    "unit": "шт",
    "moq": 50,
    "priority": "Средний",
    "showOnSite": true,
    "popular": true,
    "brand": "Nexus",
    "sort": 35,
    "image": "assets/product-rozetki-i-moduli.svg",
    "availability": "В наличии"
  },
  {
    "id": 36,
    "sourceNo": 38,
    "article": "NX-MOD-038",
    "slug": "nx-mod-038",
    "group": "Розетки и модули",
    "categorySlug": "rozetki-i-moduli",
    "subgroup": "Рамки и суппорты",
    "subcategorySlug": "rozetki-i-moduli-sub-4",
    "name": "Рамки 1/2/3/4 поста",
    "specification": "белые",
    "unit": "шт",
    "moq": 200,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 36,
    "image": "assets/product-rozetki-i-moduli.svg",
    "availability": "Под заказ"
  },
  {
    "id": 37,
    "sourceNo": 39,
    "article": "NX-MOD-039",
    "slug": "nx-mod-039",
    "group": "Розетки и модули",
    "categorySlug": "rozetki-i-moduli",
    "subgroup": "Рамки и суппорты",
    "subcategorySlug": "rozetki-i-moduli-sub-4",
    "name": "Суппорты/адаптеры 45x45",
    "specification": "под модули",
    "unit": "шт",
    "moq": 200,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 37,
    "image": "assets/product-rozetki-i-moduli.svg",
    "availability": "Под заказ"
  },
  {
    "id": 38,
    "sourceNo": 40,
    "article": "NX-MOD-040",
    "slug": "nx-mod-040",
    "group": "Розетки и модули",
    "categorySlug": "rozetki-i-moduli",
    "subgroup": "Заглушки и аксессуары",
    "subcategorySlug": "rozetki-i-moduli-sub-5",
    "name": "Заглушки 22,5x45 и 45x45",
    "specification": "белые",
    "unit": "шт",
    "moq": 200,
    "priority": "Высокий",
    "showOnSite": true,
    "popular": false,
    "brand": "Nexus",
    "sort": 38,
    "image": "assets/product-rozetki-i-moduli.svg",
    "availability": "В наличии"
  }
];
